language: python
python:
  - "3.6"

services:
  - docker

before_script:  pip install docker-compose

script:
  - docker-compose run api sh -c "python manage.py test && flake8"

environment:
  - DB_HOST=db
  - DB_NAME=app
  - DB_USER=postgres
  - DB_PASS=${DB_PASS}
  - SECRET_KEY=${SECRET_KEY}