version: "3.7"

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    env_file: .env.prod
    depends_on:
      - api
    networks:
      - app-network
    restart: always
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              (python manage.py runserver 0.0.0.0:8000 &
              (watch -n 43200 python manage.py update_db))"
    env_file: .env.prod
    depends_on:
      - db
    networks:
      - app-network
    restart: always
  db:
    container_name: db
    image: postgres:10-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file: .env.prod
    networks:
      - app-network
    restart: always
volumes:
  dbdata:
networks:
  app-network:
    driver: bridge