version: '3.7'
# docker-compose -f docker-compose.prod.yml up -d --build
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'